const chordObj = {
    A: 'A Major',
    B: 'B Major',
    C: 'C Major',
    D: 'D Major',
    E: 'E Major',
    F: 'F Major',
    G: 'G Major',
    Ab: 'Ab Major',
    Bb: 'Bb Major',
    Db: 'Db/C# Major',
    Eb: 'Eb Major',
    Gb: 'Gb/F# Major',
    Am: 'a Minor',
    Bm: 'b Minor',
    Cm: 'c Minor',
    Dm: 'd Minor',
    Em: 'e Minor',
    Fm: 'f Minor',
    Gm: 'g Minor',
    Bbm: 'a#/bb Minor',
    Dbm: 'c#/db Minor',
    Ebm: 'd#/eb Minor',
    Abm: 'g#/ab Minor',
    Gbm: 'gb/f# Minor',
    A7: 'A7',
    B7: 'B7',
    C7: 'C7',
    D7: 'D7',
    E7: 'E7',
    F7: 'F7',
    G7: 'G7',
    Ab7: 'Ab7',
    Bb7: 'Bb7',
    Db7: 'Db7/C#7',
    Eb7: 'Eb7',
    Gb7: 'Gb7/F#7'
};

export default chordObj

